import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";



import SessionWrapper from "./providers/sessionWrapper";
import CustomNavBar from "@/components/nav-bar/custom-nav-bar";

const inter = Inter({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <html lang="en" className={`${inter.className} antialiased dark text-foreground bg-background`}>
        <body>
        <SessionWrapper>
            <CustomNavBar/>
            {children}
            <ToastContainer />
          {/* <Provider>
            {children}
            
          </Provider> */}
          </SessionWrapper>
        </body>
      </html>
    
  );
}
